export const Users = [
  {
    id:1,
    profile:"profile/1.jpeg",
    username: "clone_1311",
  },
  {
    id:2,
    profile:"profile/2.jpeg",
    username: "lizel",
  },
  {
    id:3,
    profile:"profile/3.jpeg",
    username: "nisha",
  },
  {
    id:4,
    profile:"profile/4.jpeg",
    username: "ruhi",
  },
  {
    id:5,
    profile:"profile/16.jpg",
    username: "shanaya",
  },
  {
    id:6,
    profile:"profile/15.jpg",
    username: "aastha",
  },
  {
    id:7,
    profile:"profile/5.jpg",
    username: "varun sammal",
  },
  {
    id:8,
    profile:"profile/6.jpeg",
    username: "anus",
  },
  {
    id:9,
    profile:"profile/10.jpeg",
    username: "dev c++",
  },
  {
    id:10,
    profile:"profile/14.jpeg",
    username: "bhrghav@Don",
  },
];
export const Posts = [
  {
    id:1,
    desc:"Be yourself; everyone else is already taken",
    date:"5 mins ago",
    userId: 1,
    photo:"posts/13.jpeg",
    like: 32,
    comment: 9,
  },
  {
    id:2,
    desc:"I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best",
    date:"15 mins ago",
    userId: 2,
    photo:"posts/2.jpeg",
    like: 32,
    comment: 12,
  },
  {
    id:3,
    desc:"So many books, so little time",
    date:"55 mins ago",
    userId: 3,
    photo:"posts/3.jpeg",
    like: 2,
    comment: 0,
  },
  {
    id:4,
    desc:"Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.",
    date:"12 hour ago",
    userId: 4,
    photo:"posts/4.jpeg",
    like: 122,
    comment: 54,
  },
  {
    id:5,
    desc:"Be yourself; everyone else is already taken",
    date:"1 days ago",
    userId: 5,
    photo:"posts/5.jpeg",
    like: 12,
    comment: 2,
  },
  {
    id:6,
    desc:"Be yourself; everyone else is already taken",
    date:"2 days ago",
    userId: 6,
    photo:"posts/6.jpeg",
    like: 130,
    comment: 19,
  },
  {
    id:7,
    desc:"Be yourself; everyone else is already taken",
    date:"2 days ago",
    userId: 7,
    photo:"posts/7.jpeg",
    like: 327,
    comment: 93,
  },
  {
    id:8,
    desc:"Be yourself; everyone else is already taken",
    date:"6 days ago",
    userId:7,
    photo:"posts/8.jpeg",
    like: 30,
    comment: 24,
  },
  {
    id:9,
    desc:"Be yourself; everyone else is already taken",
    date:"1 week ago",
    userId: 9,
    photo:"posts/9.jpeg",
    like: 120,
    comment: 37,
  },
  {
    id:10,
    profile:"profile/12.jpeg",
    desc:"Be yourself; everyone else is already taken",
    date:"1 week ago",
    userId: 10,
    photo:"posts/10.jpeg",
    like: 45,
    comment: 12,
  }
]